### ISSUE TITLE
please provide more documentation 

### ISSUE THREAD

**Issue by mohsen0** [Ranler/boostingPL#2]
indeed very valuable job you have done.

but there is no documentation in code and for execution of program
which is not fair

regards

**Comment by Ranler** [comment]
Hi Mohsen66, 

Recently I am not focusing on this boosting algorithm.
You can read the source paper and reference this code. 
There are much more ML algorithms in Mahout Project(https://mahout.apache.org/) and have a good maintain.
Thanks.
